package example.com.umeng_plugin

/// 方法
val UMENG_PLUGIN = "umeng_plugin"
val GET_PLATFORM_VERSION = "getPlatformVersion"
val INIT = "init"
val BEGING_PAGE_VIEW = "beginPageView"
val END_PAGE_VIEW = "endPageView"
val PROFILE_SIGNIN = "profileSignIn"
val PROFILE_SIGNOFF = "profileSignOff"
val EVENT_COUNT = "eventCounts"
val SET_CATCH_UNCAUGHT = "setCatchUncaught"
val REPORT_ERR = "reportErr"
val CUSTOM_EVENT = "customEvent"
val GET_CHANNEL = "getChannel"
val GET_DEVICE_INFO = "getDeviceInfo"

/// 参数
val LOG_ENABLE = "logEnable"
val KEY = "key"
val CHANNEL = "channel"
val ENCRYPT = "encrypt"
val INTERVAL = "interval"
val REPORT_CRASH = "reportCrash"
val MODE = "mode"
val NAME = "name"
val PROVIDER = "provider"
val ID = "id"
val LABEL = "label"
val CATCH_EXCEPTION_IS_ENABLE = "catchExceptionIsEnable"
val IS_THROWABLE = "isThrowable"
val THROWABLE = "throwable"
val ERR_STRING = "errString"
val PARAMS = "params"
val EVENT_ID = "eventId"
val UMENG_CHANNEL = "UMENG_CHANNEL"
